spring:
  application:
    name: b-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: b-client
            client-secret: 2kUVsPccWuRcWHbiRP4Wj8xOOan0mDfo
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/myrealm

server:
  port: 8082